"""empty message

Revision ID: e2e5ebba2965
Revises: 
Create Date: 2020-10-01 21:34:25.395628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e5ebba2965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=80), nullable=True),
    sa.Column('guarantor', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Ledger')
    # ### end Alembic commands ###
